### ISSUE TITLE
after press hotkeys piback crash 

### ISSUE THREAD

**Issue by asakous** [jalopezsuarez/piback#1]
only work once then got Segmentation fault

**Comment by jalopezsuarez** [comment]
could you give me more details please?

**Comment by asakous** [comment]
I am using OrangPi with RetroPie installed. gcc version 4.9.2  . OS is armbian. after system boot. I ssh to host and execute nohup ./piback --ini piback.ini >/dev/null 2>&1 & then I launch fceux from emulationstation play games.  if I press the hotkey I will jump to emulationstation  menu but piback will show  Segmentation fault on console screen . here is my config [device]

device0_input = /dev/input/js0
device1_input = /dev/input/js1
device2_input = /dev/input/js2
device3_input = /dev/input/js3

[application]

application_process = fceux

[hotkey]

hotkey0_button_a = 8
hotkey0_button_b = 9

hotkey1_button_a = 8
hotkey1_button_b = 9

hotkey2_button_a = 8
hotkey2_button_b = 9

hotkey3_button_a = 8
hotkey3_button_b = 9

**Comment by jalopezsuarez** [comment]
try just one hotkey setup:

```
[device]
device0_input = /dev/input/js0
device1_input = /dev/input/js1
device2_input = /dev/input/js2
device3_input = /dev/input/js3

[application]
application_process = fceux

[hotkey]
hotkey0_button_a = 8
hotkey0_button_b = 9

hotkey1_button_a = 0
hotkey1_button_b = 0

hotkey2_button_a = 0
hotkey2_button_b = 0

hotkey3_button_a = 0
hotkey3_button_b = 0
```

anyway let me have a look if there is any problem with application_proccess property, and I will test your configuration.

**Comment by asakous** [comment]
still get Segmentation fault

**Comment by jalopezsuarez** [comment]
fixed update and try please.

**Comment by asakous** [comment]
yes . update fixed the problem.
